import { MigrationInterface, QueryRunner } from "typeorm";

export class AddDocumentosToPostulacion1778363937995 implements MigrationInterface {
    name = 'AddDocumentosToPostulacion1778363937995'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "reportes_jobs" DROP CONSTRAINT "reportes_jobs_creado_por_fkey"`);
        await queryRunner.query(`ALTER TABLE "egresados" DROP CONSTRAINT "egresados_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "empresas" DROP CONSTRAINT "empresas_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP CONSTRAINT "ofertas_empresa_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "postulaciones" DROP CONSTRAINT "postulaciones_egresado_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "postulaciones" DROP CONSTRAINT "postulaciones_oferta_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "postulacion_audit" DROP CONSTRAINT "postulacion_audit_postulacion_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "postulacion_audit" DROP CONSTRAINT "postulacion_audit_cambiado_por_fkey"`);
        await queryRunner.query(`ALTER TABLE "notificaciones" DROP CONSTRAINT "notificaciones_user_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reportes_jobs_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_role"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_google"`);
        await queryRunner.query(`DROP INDEX "public"."idx_egresados_carrera_anio"`);
        await queryRunner.query(`DROP INDEX "public"."idx_egresados_habilidades"`);
        await queryRunner.query(`DROP INDEX "public"."idx_egresados_ubicacion"`);
        await queryRunner.query(`DROP INDEX "public"."idx_empresas_verificada"`);
        await queryRunner.query(`DROP INDEX "public"."idx_empresas_sector"`);
        await queryRunner.query(`DROP INDEX "public"."idx_empresas_ubicacion"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ofertas_estado_fecha"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ofertas_empresa"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ofertas_modalidad"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ofertas_ubicacion"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ofertas_habilidades"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ofertas_salario"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ofertas_titulo_trgm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_postulaciones_egresado"`);
        await queryRunner.query(`DROP INDEX "public"."idx_postulaciones_oferta"`);
        await queryRunner.query(`DROP INDEX "public"."idx_postulaciones_fecha"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_postulacion"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notif_user_leida"`);
        await queryRunner.query(`ALTER TABLE "egresados" DROP CONSTRAINT "egresados_anio_egreso_check"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP CONSTRAINT "ofertas_salario_min_check"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP CONSTRAINT "ofertas_salario_max_check"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP CONSTRAINT "ofertas_experiencia_min_check"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP CONSTRAINT "chk_salario"`);
        await queryRunner.query(`ALTER TABLE "postulaciones" DROP CONSTRAINT "postulaciones_egresado_id_oferta_id_key"`);
        await queryRunner.query(`ALTER TABLE "postulaciones" ADD "documentos" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" DROP COLUMN "tipo"`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" ADD "tipo" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" ADD "estado" character varying NOT NULL DEFAULT 'PENDIENTE'`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" DROP COLUMN "url"`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" ADD "url" character varying`);
        await queryRunner.query(`COMMENT ON COLUMN "reportes_jobs"."pdf_base64" IS NULL`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" DROP COLUMN "creado_por"`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" ADD "creado_por" character varying`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" DROP COLUMN "creado_at"`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" ADD "creado_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" DROP COLUMN "completado_at"`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" ADD "completado_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying`);
        await queryRunner.query(`ALTER TYPE "public"."user_role" RENAME TO "user_role_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('ADMINISTRADOR', 'EGRESADO', 'EMPRESA')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'EGRESADO'`);
        await queryRunner.query(`DROP TYPE "public"."user_role_old"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_google_id_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "google_id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "google_id" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_0bd5012aeb82628e07f6a1be53b" UNIQUE ("google_id")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar_url"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar_url" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "egresados" DROP CONSTRAINT "egresados_codigo_estudiante_key"`);
        await queryRunner.query(`ALTER TABLE "egresados" DROP COLUMN "codigo_estudiante"`);
        await queryRunner.query(`ALTER TABLE "egresados" ADD "codigo_estudiante" character varying`);
        await queryRunner.query(`ALTER TABLE "egresados" ADD CONSTRAINT "UQ_5a45ab3cf2c4100f8b182976cbc" UNIQUE ("codigo_estudiante")`);
        await queryRunner.query(`ALTER TABLE "egresados" DROP COLUMN "foto_url"`);
        await queryRunner.query(`ALTER TABLE "egresados" ADD "foto_url" character varying`);
        await queryRunner.query(`ALTER TABLE "egresados" DROP COLUMN "cv_url"`);
        await queryRunner.query(`ALTER TABLE "egresados" ADD "cv_url" character varying`);
        await queryRunner.query(`ALTER TABLE "egresados" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "egresados" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "egresados" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "egresados" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "empresas" DROP COLUMN "sitio_web"`);
        await queryRunner.query(`ALTER TABLE "empresas" ADD "sitio_web" character varying`);
        await queryRunner.query(`ALTER TABLE "empresas" DROP COLUMN "logo_url"`);
        await queryRunner.query(`ALTER TABLE "empresas" ADD "logo_url" character varying`);
        await queryRunner.query(`ALTER TABLE "empresas" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "empresas" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "empresas" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "empresas" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."modalidad_oferta" RENAME TO "modalidad_oferta_old"`);
        await queryRunner.query(`CREATE TYPE "public"."ofertas_modalidad_enum" AS ENUM('PRESENCIAL', 'REMOTO', 'HIBRIDO')`);
        await queryRunner.query(`ALTER TABLE "ofertas" ALTER COLUMN "modalidad" TYPE "public"."ofertas_modalidad_enum" USING "modalidad"::"text"::"public"."ofertas_modalidad_enum"`);
        await queryRunner.query(`DROP TYPE "public"."modalidad_oferta_old"`);
        await queryRunner.query(`ALTER TABLE "ofertas" ALTER COLUMN "experiencia_min" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."estado_oferta" RENAME TO "estado_oferta_old"`);
        await queryRunner.query(`CREATE TYPE "public"."ofertas_estado_enum" AS ENUM('BORRADOR', 'ACTIVA', 'PAUSADA', 'CERRADA')`);
        await queryRunner.query(`ALTER TABLE "ofertas" ALTER COLUMN "estado" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ofertas" ALTER COLUMN "estado" TYPE "public"."ofertas_estado_enum" USING "estado"::"text"::"public"."ofertas_estado_enum"`);
        await queryRunner.query(`ALTER TABLE "ofertas" ALTER COLUMN "estado" SET DEFAULT 'BORRADOR'`);
        await queryRunner.query(`DROP TYPE "public"."estado_oferta_old"`);
        await queryRunner.query(`ALTER TABLE "ofertas" ALTER COLUMN "vistas" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."estado_postulacion" RENAME TO "estado_postulacion_old"`);
        await queryRunner.query(`CREATE TYPE "public"."postulaciones_estado_enum" AS ENUM('POSTULADO', 'EN_REVISION', 'ENTREVISTA', 'CONTRATADO', 'RECHAZADO')`);
        await queryRunner.query(`ALTER TABLE "postulaciones" ALTER COLUMN "estado" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "postulaciones" ALTER COLUMN "estado" TYPE "public"."postulaciones_estado_enum" USING "estado"::"text"::"public"."postulaciones_estado_enum"`);
        await queryRunner.query(`ALTER TABLE "postulaciones" ALTER COLUMN "estado" SET DEFAULT 'POSTULADO'`);
        await queryRunner.query(`DROP TYPE "public"."estado_postulacion_old"`);
        await queryRunner.query(`ALTER TABLE "postulaciones" DROP COLUMN "postulado_at"`);
        await queryRunner.query(`ALTER TABLE "postulaciones" ADD "postulado_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "postulaciones" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "postulaciones" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."estado_postulacion" RENAME TO "estado_postulacion_old"`);
        await queryRunner.query(`CREATE TYPE "public"."postulacion_audit_estado_anterior_enum" AS ENUM('POSTULADO', 'EN_REVISION', 'ENTREVISTA', 'CONTRATADO', 'RECHAZADO')`);
        await queryRunner.query(`ALTER TABLE "postulacion_audit" ALTER COLUMN "estado_anterior" TYPE "public"."postulacion_audit_estado_anterior_enum" USING "estado_anterior"::"text"::"public"."postulacion_audit_estado_anterior_enum"`);
        await queryRunner.query(`DROP TYPE "public"."estado_postulacion_old"`);
        await queryRunner.query(`ALTER TYPE "public"."estado_postulacion" RENAME TO "estado_postulacion_old"`);
        await queryRunner.query(`CREATE TYPE "public"."postulacion_audit_estado_nuevo_enum" AS ENUM('POSTULADO', 'EN_REVISION', 'ENTREVISTA', 'CONTRATADO', 'RECHAZADO')`);
        await queryRunner.query(`ALTER TABLE "postulacion_audit" ALTER COLUMN "estado_nuevo" TYPE "public"."postulacion_audit_estado_nuevo_enum" USING "estado_nuevo"::"text"::"public"."postulacion_audit_estado_nuevo_enum"`);
        await queryRunner.query(`DROP TYPE "public"."estado_postulacion_old"`);
        await queryRunner.query(`ALTER TABLE "postulacion_audit" DROP COLUMN "cambiado_at"`);
        await queryRunner.query(`ALTER TABLE "postulacion_audit" ADD "cambiado_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."tipo_notificacion" RENAME TO "tipo_notificacion_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notificaciones_tipo_enum" AS ENUM('CAMBIO_ESTADO', 'NUEVA_OFERTA', 'NUEVO_POSTULANTE', 'REPORTE_LISTO', 'SISTEMA')`);
        await queryRunner.query(`ALTER TABLE "notificaciones" ALTER COLUMN "tipo" TYPE "public"."notificaciones_tipo_enum" USING "tipo"::"text"::"public"."notificaciones_tipo_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tipo_notificacion_old"`);
        await queryRunner.query(`ALTER TABLE "notificaciones" DROP COLUMN "creada_at"`);
        await queryRunner.query(`ALTER TABLE "notificaciones" ADD "creada_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "postulaciones" ADD CONSTRAINT "UQ_2182001392697c852da3de91206" UNIQUE ("egresado_id", "oferta_id")`);
        await queryRunner.query(`ALTER TABLE "egresados" ADD CONSTRAINT "FK_510dd6c37b193ffedb81efaed37" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "empresas" ADD CONSTRAINT "FK_7cbf50e3a99959587a52532a3cf" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD CONSTRAINT "FK_3e3c112a192c6ed06efa32ba593" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "postulaciones" ADD CONSTRAINT "FK_53e0c8b1d258357407b51f50365" FOREIGN KEY ("egresado_id") REFERENCES "egresados"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "postulaciones" ADD CONSTRAINT "FK_daa720af7330aa5803048361675" FOREIGN KEY ("oferta_id") REFERENCES "ofertas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "postulacion_audit" ADD CONSTRAINT "FK_7631766d70c6d4b2fbcfb00aa68" FOREIGN KEY ("postulacion_id") REFERENCES "postulaciones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "postulacion_audit" ADD CONSTRAINT "FK_bed92acbb78cacdfb4099d09b9e" FOREIGN KEY ("cambiado_por") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notificaciones" ADD CONSTRAINT "FK_0a5f87551149ecc486ee8477c5f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "notificaciones" DROP CONSTRAINT "FK_0a5f87551149ecc486ee8477c5f"`);
        await queryRunner.query(`ALTER TABLE "postulacion_audit" DROP CONSTRAINT "FK_bed92acbb78cacdfb4099d09b9e"`);
        await queryRunner.query(`ALTER TABLE "postulacion_audit" DROP CONSTRAINT "FK_7631766d70c6d4b2fbcfb00aa68"`);
        await queryRunner.query(`ALTER TABLE "postulaciones" DROP CONSTRAINT "FK_daa720af7330aa5803048361675"`);
        await queryRunner.query(`ALTER TABLE "postulaciones" DROP CONSTRAINT "FK_53e0c8b1d258357407b51f50365"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP CONSTRAINT "FK_3e3c112a192c6ed06efa32ba593"`);
        await queryRunner.query(`ALTER TABLE "empresas" DROP CONSTRAINT "FK_7cbf50e3a99959587a52532a3cf"`);
        await queryRunner.query(`ALTER TABLE "egresados" DROP CONSTRAINT "FK_510dd6c37b193ffedb81efaed37"`);
        await queryRunner.query(`ALTER TABLE "postulaciones" DROP CONSTRAINT "UQ_2182001392697c852da3de91206"`);
        await queryRunner.query(`ALTER TABLE "notificaciones" DROP COLUMN "creada_at"`);
        await queryRunner.query(`ALTER TABLE "notificaciones" ADD "creada_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."tipo_notificacion_old" AS ENUM('CAMBIO_ESTADO', 'NUEVA_OFERTA', 'NUEVO_POSTULANTE', 'REPORTE_LISTO', 'SISTEMA')`);
        await queryRunner.query(`ALTER TABLE "notificaciones" ALTER COLUMN "tipo" TYPE "public"."tipo_notificacion_old" USING "tipo"::"text"::"public"."tipo_notificacion_old"`);
        await queryRunner.query(`DROP TYPE "public"."notificaciones_tipo_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."tipo_notificacion_old" RENAME TO "tipo_notificacion"`);
        await queryRunner.query(`ALTER TABLE "postulacion_audit" DROP COLUMN "cambiado_at"`);
        await queryRunner.query(`ALTER TABLE "postulacion_audit" ADD "cambiado_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."estado_postulacion_old" AS ENUM('POSTULADO', 'EN_REVISION', 'ENTREVISTA', 'CONTRATADO', 'RECHAZADO')`);
        await queryRunner.query(`ALTER TABLE "postulacion_audit" ALTER COLUMN "estado_nuevo" TYPE "public"."estado_postulacion_old" USING "estado_nuevo"::"text"::"public"."estado_postulacion_old"`);
        await queryRunner.query(`DROP TYPE "public"."postulacion_audit_estado_nuevo_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."estado_postulacion_old" RENAME TO "estado_postulacion"`);
        await queryRunner.query(`CREATE TYPE "public"."estado_postulacion_old" AS ENUM('POSTULADO', 'EN_REVISION', 'ENTREVISTA', 'CONTRATADO', 'RECHAZADO')`);
        await queryRunner.query(`ALTER TABLE "postulacion_audit" ALTER COLUMN "estado_anterior" TYPE "public"."estado_postulacion_old" USING "estado_anterior"::"text"::"public"."estado_postulacion_old"`);
        await queryRunner.query(`DROP TYPE "public"."postulacion_audit_estado_anterior_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."estado_postulacion_old" RENAME TO "estado_postulacion"`);
        await queryRunner.query(`ALTER TABLE "postulaciones" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "postulaciones" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "postulaciones" DROP COLUMN "postulado_at"`);
        await queryRunner.query(`ALTER TABLE "postulaciones" ADD "postulado_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."estado_postulacion_old" AS ENUM('POSTULADO', 'EN_REVISION', 'ENTREVISTA', 'CONTRATADO', 'RECHAZADO')`);
        await queryRunner.query(`ALTER TABLE "postulaciones" ALTER COLUMN "estado" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "postulaciones" ALTER COLUMN "estado" TYPE "public"."estado_postulacion_old" USING "estado"::"text"::"public"."estado_postulacion_old"`);
        await queryRunner.query(`ALTER TABLE "postulaciones" ALTER COLUMN "estado" SET DEFAULT 'POSTULADO'`);
        await queryRunner.query(`DROP TYPE "public"."postulaciones_estado_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."estado_postulacion_old" RENAME TO "estado_postulacion"`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ofertas" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ofertas" ALTER COLUMN "vistas" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."estado_oferta_old" AS ENUM('BORRADOR', 'ACTIVA', 'PAUSADA', 'CERRADA')`);
        await queryRunner.query(`ALTER TABLE "ofertas" ALTER COLUMN "estado" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ofertas" ALTER COLUMN "estado" TYPE "public"."estado_oferta_old" USING "estado"::"text"::"public"."estado_oferta_old"`);
        await queryRunner.query(`ALTER TABLE "ofertas" ALTER COLUMN "estado" SET DEFAULT 'BORRADOR'`);
        await queryRunner.query(`DROP TYPE "public"."ofertas_estado_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."estado_oferta_old" RENAME TO "estado_oferta"`);
        await queryRunner.query(`ALTER TABLE "ofertas" ALTER COLUMN "experiencia_min" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."modalidad_oferta_old" AS ENUM('PRESENCIAL', 'REMOTO', 'HIBRIDO')`);
        await queryRunner.query(`ALTER TABLE "ofertas" ALTER COLUMN "modalidad" TYPE "public"."modalidad_oferta_old" USING "modalidad"::"text"::"public"."modalidad_oferta_old"`);
        await queryRunner.query(`DROP TYPE "public"."ofertas_modalidad_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."modalidad_oferta_old" RENAME TO "modalidad_oferta"`);
        await queryRunner.query(`ALTER TABLE "empresas" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "empresas" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "empresas" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "empresas" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "empresas" DROP COLUMN "logo_url"`);
        await queryRunner.query(`ALTER TABLE "empresas" ADD "logo_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "empresas" DROP COLUMN "sitio_web"`);
        await queryRunner.query(`ALTER TABLE "empresas" ADD "sitio_web" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "egresados" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "egresados" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "egresados" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "egresados" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "egresados" DROP COLUMN "cv_url"`);
        await queryRunner.query(`ALTER TABLE "egresados" ADD "cv_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "egresados" DROP COLUMN "foto_url"`);
        await queryRunner.query(`ALTER TABLE "egresados" ADD "foto_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "egresados" DROP CONSTRAINT "UQ_5a45ab3cf2c4100f8b182976cbc"`);
        await queryRunner.query(`ALTER TABLE "egresados" DROP COLUMN "codigo_estudiante"`);
        await queryRunner.query(`ALTER TABLE "egresados" ADD "codigo_estudiante" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "egresados" ADD CONSTRAINT "egresados_codigo_estudiante_key" UNIQUE ("codigo_estudiante")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar_url"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_0bd5012aeb82628e07f6a1be53b"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "google_id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "google_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_google_id_key" UNIQUE ("google_id")`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_old" AS ENUM('ADMINISTRADOR', 'EGRESADO', 'EMPRESA')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."user_role_old" USING "role"::"text"::"public"."user_role_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'EGRESADO'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_old" RENAME TO "user_role"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" DROP COLUMN "completado_at"`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" ADD "completado_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" DROP COLUMN "creado_at"`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" ADD "creado_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" DROP COLUMN "creado_por"`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" ADD "creado_por" uuid`);
        await queryRunner.query(`COMMENT ON COLUMN "reportes_jobs"."pdf_base64" IS 'PDF generado codificado en base64. Reemplaza el almacenamiento en disco para compatibilidad con plataformas cloud efímeras.'`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" DROP COLUMN "url"`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" ADD "url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" ADD "estado" character varying(50) NOT NULL DEFAULT 'PENDIENTE'`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" DROP COLUMN "tipo"`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" ADD "tipo" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "postulaciones" DROP COLUMN "documentos"`);
        await queryRunner.query(`ALTER TABLE "postulaciones" ADD CONSTRAINT "postulaciones_egresado_id_oferta_id_key" UNIQUE ("egresado_id", "oferta_id")`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD CONSTRAINT "chk_salario" CHECK (((salario_max IS NULL) OR (salario_min IS NULL) OR (salario_max >= salario_min)))`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD CONSTRAINT "ofertas_experiencia_min_check" CHECK ((experiencia_min >= 0))`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD CONSTRAINT "ofertas_salario_max_check" CHECK ((salario_max > (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD CONSTRAINT "ofertas_salario_min_check" CHECK ((salario_min > (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "egresados" ADD CONSTRAINT "egresados_anio_egreso_check" CHECK (((anio_egreso >= 1980) AND (anio_egreso <= 2100)))`);
        await queryRunner.query(`CREATE INDEX "idx_notif_user_leida" ON "notificaciones" ("creada_at", "leida", "user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_postulacion" ON "postulacion_audit" ("cambiado_at", "postulacion_id") `);
        await queryRunner.query(`CREATE INDEX "idx_postulaciones_fecha" ON "postulaciones" ("postulado_at") `);
        await queryRunner.query(`CREATE INDEX "idx_postulaciones_oferta" ON "postulaciones" ("estado", "oferta_id") `);
        await queryRunner.query(`CREATE INDEX "idx_postulaciones_egresado" ON "postulaciones" ("egresado_id", "estado", "postulado_at") `);
        await queryRunner.query(`CREATE INDEX "idx_ofertas_titulo_trgm" ON "ofertas" ("titulo") `);
        await queryRunner.query(`CREATE INDEX "idx_ofertas_salario" ON "ofertas" ("salario_max", "salario_min") WHERE (estado = 'ACTIVA'::estado_oferta)`);
        await queryRunner.query(`CREATE INDEX "idx_ofertas_habilidades" ON "ofertas" ("habilidades_req") `);
        await queryRunner.query(`CREATE INDEX "idx_ofertas_ubicacion" ON "ofertas" ("estado", "ubicacion") `);
        await queryRunner.query(`CREATE INDEX "idx_ofertas_modalidad" ON "ofertas" ("estado", "modalidad") `);
        await queryRunner.query(`CREATE INDEX "idx_ofertas_empresa" ON "ofertas" ("empresa_id", "estado") `);
        await queryRunner.query(`CREATE INDEX "idx_ofertas_estado_fecha" ON "ofertas" ("estado", "publicada_at") WHERE (estado = 'ACTIVA'::estado_oferta)`);
        await queryRunner.query(`CREATE INDEX "idx_empresas_ubicacion" ON "empresas" ("ubicacion") `);
        await queryRunner.query(`CREATE INDEX "idx_empresas_sector" ON "empresas" ("sector") `);
        await queryRunner.query(`CREATE INDEX "idx_empresas_verificada" ON "empresas" ("verificada") WHERE (verificada = true)`);
        await queryRunner.query(`CREATE INDEX "idx_egresados_ubicacion" ON "egresados" ("ubicacion") WHERE (ubicacion IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_egresados_habilidades" ON "egresados" ("habilidades") `);
        await queryRunner.query(`CREATE INDEX "idx_egresados_carrera_anio" ON "egresados" ("anio_egreso", "carrera") `);
        await queryRunner.query(`CREATE INDEX "idx_users_google" ON "users" ("google_id") WHERE (google_id IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_users_role" ON "users" ("role") WHERE (is_active = true)`);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_reportes_jobs_user" ON "reportes_jobs" ("creado_at", "creado_por") `);
        await queryRunner.query(`ALTER TABLE "notificaciones" ADD CONSTRAINT "notificaciones_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "postulacion_audit" ADD CONSTRAINT "postulacion_audit_cambiado_por_fkey" FOREIGN KEY ("cambiado_por") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "postulacion_audit" ADD CONSTRAINT "postulacion_audit_postulacion_id_fkey" FOREIGN KEY ("postulacion_id") REFERENCES "postulaciones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "postulaciones" ADD CONSTRAINT "postulaciones_oferta_id_fkey" FOREIGN KEY ("oferta_id") REFERENCES "ofertas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "postulaciones" ADD CONSTRAINT "postulaciones_egresado_id_fkey" FOREIGN KEY ("egresado_id") REFERENCES "egresados"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ofertas" ADD CONSTRAINT "ofertas_empresa_id_fkey" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "empresas" ADD CONSTRAINT "empresas_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "egresados" ADD CONSTRAINT "egresados_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reportes_jobs" ADD CONSTRAINT "reportes_jobs_creado_por_fkey" FOREIGN KEY ("creado_por") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
